"""Project scaffolding for `archtool init`.

Generates a new project directory with a minimal, valid starter building
and a quick-start README — not a worked showcase (see `examples/` in the
archtool repository for that), just enough to validate/build immediately
and extend from.
"""

from __future__ import annotations

from pathlib import Path

STARTER_YAML = """\
# {name} — archtool building file.
# Edit freely; run `archtool validate` after every change.
# Format reference: SPEC.md in the archtool project.

building:
  name: "{name}"
  ceiling_height: 250
  exterior_wall_thickness: 20
  partition_wall_thickness: 10
  unit: "cm"
  format_version: "1.0"
  spec: "SPEC.md"

# outline defines the building perimeter as a list of [x, y] coordinate
# pairs (in cm; x right, y down), in perimeter order.  The tool auto-labels
# distinct x-values as vertical gridlines "1","2",... and distinct y-values
# as horizontal gridlines "A","B",..., drawn as dashed reference lines in
# the SVG, and derives each point's id from them: o<x_label><y_label>.
# Here that gives P1->o1A, P2->o2A, P3->o2B, P4->o1B - refer to them by
# those ids elsewhere in this file.  A point may still be given explicit
# `id` / `x_axis` / `y_axis` (object form) to override the automatic ones.
outline:
  - [0, 0]      # o1A
  - [400, 0]    # o2A
  - [400, 300]  # o2B
  - [0, 300]    # o1B

# Additional named points not on the outline (interior T-junctions,
# opening endpoints, etc.).  Omit if all referenced points are in outline.
points:
  D1a: [50, 0]
  D1b: [150, 0]
  R1: [20, 20]
  R2: [380, 20]
  R3: [380, 280]
  R4: [20, 280]

walls: []
# Add interior walls like:
#   - id: "W1"
#     from: o1A
#     to: o2A
#     type: "partition"   # or "load_bearing"
#     # thickness is optional; defaults to partition_wall_thickness or
#     # exterior_wall_thickness from the building block above.

openings:
  - id: "D1"
    type: "door"
    from: D1a
    to: D1b
    sill: 0
    height: 200

rooms:
  - id: "main"
    name: "Main room"
    floor: "wood"   # wood | tiles | laminate | concrete | carpet
    outline: [R1, R2, R3, R4]
"""

STARTER_README = """\
# {name}

A building project for **archtool** — a compiler for buildings. \
`dom_dane.yaml` is the single source of truth; archtool turns it into a \
floor-plan SVG (and, in future versions, more deliverables).

## Quick start

```
archtool validate dom_dane.yaml        # schema + geometry checks
archtool build dom_dane.yaml           # validate, then render dom_dane.svg
archtool build dom_dane.yaml --watch   # re-render on every save
```

## Editing the building

- `building:` — overall properties (ceiling height, wall thicknesses, ...).
- `outline:` — the building's exterior perimeter as a list of `[x, y]`
  coordinate pairs (cm; x right, y down).  Closes automatically (don't
  repeat the first point).  Point ids and grid-axis labels ("1","2",...
  and "A","B",...) are derived automatically from the coordinates
  (`o<x_label><y_label>`); give a point explicit `id` / `x_axis` /
  `y_axis` (object form) only to override the automatic ones.
- `points:` — additional named coordinates that don't appear on the
  outline (interior junction points, opening endpoints, etc.).
- `walls:` — interior walls: a `from`/`to` point pair, `type`
  (`"load_bearing"` or `"partition"`), and optional `thickness`
  (defaults to the building's `exterior_wall_thickness` or
  `partition_wall_thickness` when omitted).
- `openings:` — doors and windows: a `from`/`to` span on a wall's axis,
  plus `sill` and `height`.
- `rooms:` — named polygons (point lists) with a `floor` material.

This starter has one room and one door — extend it by adding more points,
walls, openings, and rooms following the same pattern. Run
`archtool validate` after every change; error messages name the offending
element and the reason.

For the full format reference, see SPEC.md in the archtool project.

---
Generated by `archtool init`.
"""


def init_project(directory: Path, name: str) -> None:
    """Write a minimal starter building project into `directory`.

    `directory` must not already exist; the caller is responsible for that
    check so it can report a precise error.
    """
    directory.mkdir(parents=True)
    (directory / "dom_dane.yaml").write_text(STARTER_YAML.format(name=name), encoding="utf-8")
    (directory / "README.md").write_text(STARTER_README.format(name=name), encoding="utf-8")
