"""Project scaffolding for `archtool init`.

Generates a new project directory with a minimal, valid starter building
and a quick-start README — not a worked showcase (see `examples/` in the
archtool repository for that), just enough to validate/build immediately
and extend from.
"""

from __future__ import annotations

from pathlib import Path

STARTER_YAML = """\
# {name} — archtool building file.
# Edit freely; run `archtool validate` after every change.
# Format reference: SPEC.md in the archtool project.

building:
  name: "{name}"
  ceiling_height: 250
  exterior_wall_thickness: 20
  partition_wall_thickness: 10
  unit: "cm"
  format_version: "1.0"
  spec: "SPEC.md"

points:
  # Every coordinate used anywhere is named once here, in centimetres.
  # [x, y]: x increases right, y increases down.
  P1: [0, 0]
  P2: [400, 0]
  P3: [400, 300]
  P4: [0, 300]
  D1a: [50, 0]
  D1b: [150, 0]
  R1: [20, 20]
  R2: [380, 20]
  R3: [380, 280]
  R4: [20, 280]

outline: [P1, P2, P3, P4]

walls: []
# Add interior walls like:
#   - id: "W1"
#     from: P1
#     to: P2
#     thickness: 10
#     type: "partition"   # or "load_bearing"

openings:
  - id: "D1"
    type: "door"
    from: D1a
    to: D1b
    sill: 0
    height: 200

rooms:
  - id: "main"
    name: "Main room"
    floor: "wood"   # wood | tiles | laminate | concrete | carpet
    outline: [R1, R2, R3, R4]
"""

STARTER_README = """\
# {name}

A building project for **archtool** — a compiler for buildings. \
`dom_dane.yaml` is the single source of truth; archtool turns it into a \
floor-plan SVG (and, in future versions, more deliverables).

## Quick start

```
archtool validate dom_dane.yaml        # schema + geometry checks
archtool build dom_dane.yaml           # validate, then render dom_dane.svg
archtool build dom_dane.yaml --watch   # re-render on every save
```

## Editing the building

- `building:` — overall properties (ceiling height, wall thicknesses, ...).
- `points:` — every coordinate used anywhere, named once, in centimetres.
  `[x, y]`, x increases right, y increases down.
- `outline:` — the building's exterior wall, as a list of point names in
  perimeter order. Closes automatically (don't repeat the first point).
- `walls:` — interior walls: a `from`/`to` point pair, `thickness`, and
  `type` (`"load_bearing"` or `"partition"`).
- `openings:` — doors and windows: a `from`/`to` span on a wall's axis,
  plus `sill` and `height`.
- `rooms:` — named polygons (point lists) with a `floor` material.

This starter has one room and one door — extend it by adding more points,
walls, openings, and rooms following the same pattern. Run
`archtool validate` after every change; error messages name the offending
element and the reason.

For the full format reference, see SPEC.md in the archtool project.

---
Generated by `archtool init`.
"""


def init_project(directory: Path, name: str) -> None:
    """Write a minimal starter building project into `directory`.

    `directory` must not already exist; the caller is responsible for that
    check so it can report a precise error.
    """
    directory.mkdir(parents=True)
    (directory / "dom_dane.yaml").write_text(STARTER_YAML.format(name=name), encoding="utf-8")
    (directory / "README.md").write_text(STARTER_README.format(name=name), encoding="utf-8")
